sonar.projectKey=eco-backend
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.token=sqp_5c61b2fbee6f277f29c77f99b6610952a4969d03

# Filtros para TypeScript que pusimos antes:
sonar.inclusions=src/**/*.ts
sonar.exclusions=src/**/*.spec.ts,src/**/*.e2e-spec.ts

sonar.coverage.exclusions=src/**/*.entity.ts,src/**/*.dto.ts,src/**/*.module.ts,src/**/*.guard.ts,src/**/*.types.ts,src/**/*.enum.ts,src/main.ts,src/config/**,src/admin/**,src/**/*.controller.ts,src/recycling-centers/**,src/database/typeorm.config.ts

sonar.typescript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPath=tsconfig.json