export const rewardCatalog = [
  {
    id: '1',
    title: '15% dcto. Supermercados Wong',
    cost: 500,
    category: 'Compras',
    icon: 'shopping-bag',
    color: 'bg-blue-500',
    available: true,
  },
  {
    id: '2',
    title: 'Café gratis en Starbucks',
    cost: 300,
    category: 'Alimentos',
    icon: 'coffee',
    color: 'bg-amber-600',
    available: true,
  },
  {
    id: '3',
    title: '1 mes BiciLima Premium',
    cost: 800,
    category: 'Transporte',
    icon: 'bike',
    color: 'bg-green-600',
    available: true,
  },
  {
    id: '4',
    title: 'Bolsa reutilizable EcoTrack',
    cost: 150,
    category: 'Merch',
    icon: 'gift',
    color: 'bg-purple-500',
    available: true,
  },
  {
    id: '5',
    title: 'Donación a ONG ambiental',
    cost: 200,
    category: 'Impacto',
    icon: 'star',
    color: 'bg-emerald-500',
    available: true,
  },
  {
    id: '6',
    title: '20% dcto. Plaza Vea',
    cost: 600,
    category: 'Compras',
    icon: 'shopping-bag',
    color: 'bg-red-500',
    available: false,
  },
] as const;
